services:
  mcp_polygon:
    build: .
    volumes:
      - .:/app
    container_name: mcp_polygon_server
    environment:
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    stdin_open: true
    tty: true
